<?php

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('country')->insert(['name' => 'Afghanistan','iso' => 'AF','isd' => '93']);
		DB::table('country')->insert(['name' => 'Albania','iso' => 'AL','isd' => '355']);
		DB::table('country')->insert(['name' => 'Algeria','iso' => 'DZ','isd' => '213']);
		DB::table('country')->insert(['name' => 'American Samoa','iso' => 'AS','isd' => '1-684']);
		DB::table('country')->insert(['name' => 'Andorra','iso' => 'AD','isd' => '376']);
		DB::table('country')->insert(['name' => 'Angola','iso' => 'AO','isd' => '244']);
		DB::table('country')->insert(['name' => 'Anguilla','iso' => 'AI','isd' => '1-264']);
		DB::table('country')->insert(['name' => 'Antarctica','iso' => 'AQ','isd' => '672']);
		DB::table('country')->insert(['name' => 'Antigua and Barbuda','iso' => 'AG','isd' => '1-268']);
		DB::table('country')->insert(['name' => 'Argentina','iso' => 'AR','isd' => '54']);
		DB::table('country')->insert(['name' => 'Armenia','iso' => 'AM','isd' => '374']);
		DB::table('country')->insert(['name' => 'Aruba','iso' => 'AW','isd' => '297']);
		DB::table('country')->insert(['name' => 'Australia','iso' => 'AU','isd' => '61']);
		DB::table('country')->insert(['name' => 'Austria','iso' => 'AT','isd' => '43']);
		DB::table('country')->insert(['name' => 'Azerbaijan','iso' => 'AZ','isd' => '994']);
		DB::table('country')->insert(['name' => 'Bahamas','iso' => 'BS','isd' => '1-242']);
		DB::table('country')->insert(['name' => 'Bahrain','iso' => 'BH','isd' => '973']);
		DB::table('country')->insert(['name' => 'Bangladesh','iso' => 'BD','isd' => '880']);
		DB::table('country')->insert(['name' => 'Barbados','iso' => 'BB','isd' => '1-246']);
		DB::table('country')->insert(['name' => 'Belarus','iso' => 'BY','isd' => '375']);
		DB::table('country')->insert(['name' => 'Belgium','iso' => 'BE','isd' => '32']);
		DB::table('country')->insert(['name' => 'Belize','iso' => 'BZ','isd' => '501']);
		DB::table('country')->insert(['name' => 'Benin','iso' => 'BJ','isd' => '229']);
		DB::table('country')->insert(['name' => 'Bermuda','iso' => 'BM','isd' => '1-441']);
		DB::table('country')->insert(['name' => 'Bhutan','iso' => 'BT','isd' => '975']);
		DB::table('country')->insert(['name' => 'Bolivia','iso' => 'BO','isd' => '591']);
		DB::table('country')->insert(['name' => 'Bosnia and Herzegowina','iso' => 'BA','isd' => '387']);
		DB::table('country')->insert(['name' => 'Botswana','iso' => 'BW','isd' => '267']);
		DB::table('country')->insert(['name' => 'Bouvet Island','iso' => 'BV','isd' => '47']);
		DB::table('country')->insert(['name' => 'Brazil','iso' => 'BR','isd' => '55']);
		DB::table('country')->insert(['name' => 'British Indian Ocean Territory','iso' => 'IO','isd' => '246']);
		DB::table('country')->insert(['name' => 'Brunei Darussalam','iso' => 'BN','isd' => '673']);
		DB::table('country')->insert(['name' => 'Bulgaria','iso' => 'BG','isd' => '359']);
		DB::table('country')->insert(['name' => 'Burkina Faso','iso' => 'BF','isd' => '226']);
		DB::table('country')->insert(['name' => 'Burundi','iso' => 'BI','isd' => '257']);
		DB::table('country')->insert(['name' => 'Cambodia','iso' => 'KH','isd' => '855']);
		DB::table('country')->insert(['name' => 'Cameroon','iso' => 'CM','isd' => '237']);
		DB::table('country')->insert(['name' => 'Canada','iso' => 'CA','isd' => '1']);
		DB::table('country')->insert(['name' => 'Cape Verde','iso' => 'CV','isd' => '238']);
		DB::table('country')->insert(['name' => 'Cayman Islands','iso' => 'KY','isd' => '1-345']);
		DB::table('country')->insert(['name' => 'Central African Republic','iso' => 'CF','isd' => '236']);
		DB::table('country')->insert(['name' => 'Chad','iso' => 'TD','isd' => '235']);
		DB::table('country')->insert(['name' => 'Chile','iso' => 'CL','isd' => '56']);
		DB::table('country')->insert(['name' => 'China','iso' => 'CN','isd' => '86']);
		DB::table('country')->insert(['name' => 'Christmas Island','iso' => 'CX','isd' => '61']);
		DB::table('country')->insert(['name' => 'Cocos (Keeling) Islands','iso' => 'CC','isd' => '61']);
		DB::table('country')->insert(['name' => 'Colombia','iso' => 'CO','isd' => '57']);
		DB::table('country')->insert(['name' => 'Comoros','iso' => 'KM','isd' => '269']);
		DB::table('country')->insert(['name' => 'Congo Democratic Republic of','iso' => 'CG','isd' => '242']);
		DB::table('country')->insert(['name' => 'Cook Islands','iso' => 'CK','isd' => '682']);
		DB::table('country')->insert(['name' => 'Costa Rica','iso' => 'CR','isd' => '506']);
		DB::table('country')->insert(['name' => 'Croatia','iso' => 'HR','isd' => '385']);
		DB::table('country')->insert(['name' => 'Cuba','iso' => 'CU','isd' => '53']);
		DB::table('country')->insert(['name' => 'Cyprus','iso' => 'CY','isd' => '357']);
		DB::table('country')->insert(['name' => 'Czech Republic','iso' => 'CZ','isd' => '420']);
		DB::table('country')->insert(['name' => 'Denmark','iso' => 'DK','isd' => '45']);
		DB::table('country')->insert(['name' => 'Djibouti','iso' => 'DJ','isd' => '253']);
		DB::table('country')->insert(['name' => 'Dominica','iso' => 'DM','isd' => '1-767']);
		DB::table('country')->insert(['name' => 'Dominican Republic','iso' => 'DO','isd' => '1-809']);
		DB::table('country')->insert(['name' => 'Timor-Leste','iso' => 'TL','isd' => '670']);
		DB::table('country')->insert(['name' => 'Ecuador','iso' => 'EC','isd' => '593']);
		DB::table('country')->insert(['name' => 'Egypt','iso' => 'EG','isd' => '20']);
		DB::table('country')->insert(['name' => 'El Salvador','iso' => 'SV','isd' => '503']);
		DB::table('country')->insert(['name' => 'Equatorial Guinea','iso' => 'GQ','isd' => '240']);
		DB::table('country')->insert(['name' => 'Eritrea','iso' => 'ER','isd' => '291']);
		DB::table('country')->insert(['name' => 'Estonia','iso' => 'EE','isd' => '372']);
		DB::table('country')->insert(['name' => 'Ethiopia','iso' => 'ET','isd' => '251']);
		DB::table('country')->insert(['name' => 'Falkland Islands (Malvinas)','iso' => 'FK','isd' => '500']);
		DB::table('country')->insert(['name' => 'Faroe Islands','iso' => 'FO','isd' => '298']);
		DB::table('country')->insert(['name' => 'Fiji','iso' => 'FJ','isd' => '679']);
		DB::table('country')->insert(['name' => 'Finland','iso' => 'FI','isd' => '358']);
		DB::table('country')->insert(['name' => 'France','iso' => 'FR','isd' => '33']);
		DB::table('country')->insert(['name' => 'French Guiana','iso' => 'GF','isd' => '594']);
		DB::table('country')->insert(['name' => 'French Polynesia','iso' => 'PF','isd' => '689']);
		DB::table('country')->insert(['name' => 'French Southern Territories','iso' => 'TF','isd' => 'NULL']);
		DB::table('country')->insert(['name' => 'Gabon','iso' => 'GA','isd' => '241']);
		DB::table('country')->insert(['name' => 'Gambia','iso' => 'GM','isd' => '220']);
		DB::table('country')->insert(['name' => 'Georgia','iso' => 'GE','isd' => '995']);
		DB::table('country')->insert(['name' => 'Germany','iso' => 'DE','isd' => '49']);
		DB::table('country')->insert(['name' => 'Ghana','iso' => 'GH','isd' => '233']);
		DB::table('country')->insert(['name' => 'Gibraltar','iso' => 'GI','isd' => '350']);
		DB::table('country')->insert(['name' => 'Greece','iso' => 'GR','isd' => '30']);
		DB::table('country')->insert(['name' => 'Greenland','iso' => 'GL','isd' => '299']);
		DB::table('country')->insert(['name' => 'Grenada','iso' => 'GD','isd' => '1-473']);
		DB::table('country')->insert(['name' => 'Guadeloupe','iso' => 'GP','isd' => '590']);
		DB::table('country')->insert(['name' => 'Guam','iso' => 'GU','isd' => '1-671']);
		DB::table('country')->insert(['name' => 'Guatemala','iso' => 'GT','isd' => '502']);
		DB::table('country')->insert(['name' => 'Guinea','iso' => 'GN','isd' => '224']);
		DB::table('country')->insert(['name' => 'Guinea-bissau','iso' => 'GW','isd' => '245']);
		DB::table('country')->insert(['name' => 'Guyana','iso' => 'GY','isd' => '592']);
		DB::table('country')->insert(['name' => 'Haiti','iso' => 'HT','isd' => '509']);
		DB::table('country')->insert(['name' => 'Heard Island and McDonald Islands','iso' => 'HM','isd' => '11']);
		DB::table('country')->insert(['name' => 'Honduras','iso' => 'HN','isd' => '504']);
		DB::table('country')->insert(['name' => 'Hong Kong','iso' => 'HK','isd' => '852']);
		DB::table('country')->insert(['name' => 'Hungary','iso' => 'HU','isd' => '36']);
		DB::table('country')->insert(['name' => 'Iceland','iso' => 'IS','isd' => '354']);
		DB::table('country')->insert(['name' => 'India','iso' => 'IN','isd' => '91']);
		DB::table('country')->insert(['name' => 'Indonesia','iso' => 'ID','isd' => '62']);
		DB::table('country')->insert(['name' => 'Iran (Islamic Republic of)','iso' => 'IR','isd' => '98']);
		DB::table('country')->insert(['name' => 'Iraq','iso' => 'IQ','isd' => '964']);
		DB::table('country')->insert(['name' => 'Ireland','iso' => 'IE','isd' => '353']);
		DB::table('country')->insert(['name' => 'Israel','iso' => 'IL','isd' => '972']);
		DB::table('country')->insert(['name' => 'Italy','iso' => 'IT','isd' => '39']);
		DB::table('country')->insert(['name' => 'Jamaica','iso' => 'JM','isd' => '1-876']);
		DB::table('country')->insert(['name' => 'Japan','iso' => 'JP','isd' => '81']);
		DB::table('country')->insert(['name' => 'Jordan','iso' => 'JO','isd' => '962']);
		DB::table('country')->insert(['name' => 'Kazakhstan','iso' => 'KZ','isd' => '7']);
		DB::table('country')->insert(['name' => 'Kenya','iso' => 'KE','isd' => '254']);
		DB::table('country')->insert(['name' => 'Kiribati','iso' => 'KI','isd' => '686']);
		DB::table('country')->insert(['name' => 'Korea','iso' => 'KP','isd' => '850']);
		DB::table('country')->insert(['name' => 'South Korea','iso' => 'KR','isd' => '82']);
		DB::table('country')->insert(['name' => 'Kuwait','iso' => 'KW','isd' => '965']);
		DB::table('country')->insert(['name' => 'Kyrgyzstan','iso' => 'KG','isd' => '996']);
		DB::table('country')->insert(['name' => 'Lao Peoples Democratic Republic','iso' => 'LA','isd' => '856']);
		DB::table('country')->insert(['name' => 'Latvia','iso' => 'LV','isd' => '371']);
		DB::table('country')->insert(['name' => 'Lebanon','iso' => 'LB','isd' => '961']);
		DB::table('country')->insert(['name' => 'Lesotho','iso' => 'LS','isd' => '266']);
		DB::table('country')->insert(['name' => 'Liberia','iso' => 'LR','isd' => '231']);
		DB::table('country')->insert(['name' => 'Libya','iso' => 'LY','isd' => '218']);
		DB::table('country')->insert(['name' => 'Liechtenstein','iso' => 'LI','isd' => '423']);
		DB::table('country')->insert(['name' => 'Lithuania','iso' => 'LT','isd' => '370']);
		DB::table('country')->insert(['name' => 'Luxembourg','iso' => 'LU','isd' => '352']);
		DB::table('country')->insert(['name' => 'Macao','iso' => 'MO','isd' => '853']);
		DB::table('country')->insert(['name' => 'Macedonia, The Former Yugoslav Republic of','iso' => 'MK','isd' => '389']);
		DB::table('country')->insert(['name' => 'Madagascar','iso' => 'MG','isd' => '261']);
		DB::table('country')->insert(['name' => 'Malawi','iso' => 'MW','isd' => '265']);
		DB::table('country')->insert(['name' => 'Malaysia','iso' => 'MY','isd' => '60']);
		DB::table('country')->insert(['name' => 'Maldives','iso' => 'MV','isd' => '960']);
		DB::table('country')->insert(['name' => 'Mali','iso' => 'ML','isd' => '223']);
		DB::table('country')->insert(['name' => 'Malta','iso' => 'MT','isd' => '356']);
		DB::table('country')->insert(['name' => 'Marshall Islands','iso' => 'MH','isd' => '692']);
		DB::table('country')->insert(['name' => 'Martinique','iso' => 'MQ','isd' => '596']);
		DB::table('country')->insert(['name' => 'Mauritania','iso' => 'MR','isd' => '222']);
		DB::table('country')->insert(['name' => 'Mauritius','iso' => 'MU','isd' => '230']);
		DB::table('country')->insert(['name' => 'Mayotte','iso' => 'YT','isd' => '262']);
		DB::table('country')->insert(['name' => 'Mexico','iso' => 'MX','isd' => '52']);
		DB::table('country')->insert(['name' => 'Micronesia, Federated States of','iso' => 'FM','isd' => '691']);
		DB::table('country')->insert(['name' => 'Moldova','iso' => 'MD','isd' => '373']);
		DB::table('country')->insert(['name' => 'Monaco','iso' => 'MC','isd' => '377']);
		DB::table('country')->insert(['name' => 'Mongolia','iso' => 'MN','isd' => '976']);
		DB::table('country')->insert(['name' => 'Montserrat','iso' => 'MS','isd' => '1-664']);
		DB::table('country')->insert(['name' => 'Morocco','iso' => 'MA','isd' => '212']);
		DB::table('country')->insert(['name' => 'Mozambique','iso' => 'MZ','isd' => '258']);
		DB::table('country')->insert(['name' => 'Myanmar','iso' => 'MM','isd' => '95']);
		DB::table('country')->insert(['name' => 'Namibia','iso' => 'NA','isd' => '264']);
		DB::table('country')->insert(['name' => 'Nauru','iso' => 'NR','isd' => '674']);
		DB::table('country')->insert(['name' => 'Nepal','iso' => 'NP','isd' => '977']);
		DB::table('country')->insert(['name' => 'Netherlands','iso' => 'NL','isd' => '31']);
		DB::table('country')->insert(['name' => 'Netherlands Antilles','iso' => 'AN','isd' => '599']);
		DB::table('country')->insert(['name' => 'New Caledonia','iso' => 'NC','isd' => '687']);
		DB::table('country')->insert(['name' => 'New Zealand','iso' => 'NZ','isd' => '64']);
		DB::table('country')->insert(['name' => 'Nicaragua','iso' => 'NI','isd' => '505']);
		DB::table('country')->insert(['name' => 'Niger','iso' => 'NE','isd' => '227']);
		DB::table('country')->insert(['name' => 'Nigeria','iso' => 'NG','isd' => '234']);
		DB::table('country')->insert(['name' => 'Niue','iso' => 'NU','isd' => '683']);
		DB::table('country')->insert(['name' => 'Norfolk Island','iso' => 'NF','isd' => '672']);
		DB::table('country')->insert(['name' => 'Northern Mariana Islands','iso' => 'MP','isd' => '1-670']);
		DB::table('country')->insert(['name' => 'Norway','iso' => 'NO','isd' => '47']);
		DB::table('country')->insert(['name' => 'Oman','iso' => 'OM','isd' => '968']);
		DB::table('country')->insert(['name' => 'Pakistan','iso' => 'PK','isd' => '92']);
		DB::table('country')->insert(['name' => 'Palau','iso' => 'PW','isd' => '680']);
		DB::table('country')->insert(['name' => 'Panama','iso' => 'PA','isd' => '507']);
		DB::table('country')->insert(['name' => 'Papua New Guinea','iso' => 'PG','isd' => '675']);
		DB::table('country')->insert(['name' => 'Paraguay','iso' => 'PY','isd' => '595']);
		DB::table('country')->insert(['name' => 'Peru','iso' => 'PE','isd' => '51']);
		DB::table('country')->insert(['name' => 'Philippines','iso' => 'PH','isd' => '63']);
		DB::table('country')->insert(['name' => 'Pitcairn','iso' => 'PN','isd' => '64']);
		DB::table('country')->insert(['name' => 'Poland','iso' => 'PL','isd' => '48']);
		DB::table('country')->insert(['name' => 'Portugal','iso' => 'PT','isd' => '351']);
		DB::table('country')->insert(['name' => 'Puerto Rico','iso' => 'PR','isd' => '1-787']);
		DB::table('country')->insert(['name' => 'Qatar','iso' => 'QA','isd' => '974']);
		DB::table('country')->insert(['name' => 'Reunion','iso' => 'RE','isd' => '262']);
		DB::table('country')->insert(['name' => 'Romania','iso' => 'RO','isd' => '40']);
		DB::table('country')->insert(['name' => 'Russian Federation','iso' => 'RU','isd' => '7']);
		DB::table('country')->insert(['name' => 'Rwanda','iso' => 'RW','isd' => '250']);
		DB::table('country')->insert(['name' => 'Saint Kitts and Nevis','iso' => 'KN','isd' => '1-869']);
		DB::table('country')->insert(['name' => 'Saint Lucia','iso' => 'LC','isd' => '1-758']);
		DB::table('country')->insert(['name' => 'Saint Vincent and the Grenadines','iso' => 'VC','isd' => '1-784']);
		DB::table('country')->insert(['name' => 'Samoa','iso' => 'WS','isd' => '685']);
		DB::table('country')->insert(['name' => 'San Marino','iso' => 'SM','isd' => '378']);
		DB::table('country')->insert(['name' => 'Sao Tome and Principe','iso' => 'ST','isd' => '239']);
		DB::table('country')->insert(['name' => 'Saudi Arabia','iso' => 'SA','isd' => '966']);
		DB::table('country')->insert(['name' => 'Senegal','iso' => 'SN','isd' => '221']);
		DB::table('country')->insert(['name' => 'Seychelles','iso' => 'SC','isd' => '248']);
		DB::table('country')->insert(['name' => 'Sierra Leone','iso' => 'SL','isd' => '232']);
		DB::table('country')->insert(['name' => 'Singapore','iso' => 'SG','isd' => '65']);
		DB::table('country')->insert(['name' => 'Slovakia (Slovak Republic)','iso' => 'SK','isd' => '421']);
		DB::table('country')->insert(['name' => 'Slovenia','iso' => 'SI','isd' => '386']);
		DB::table('country')->insert(['name' => 'Solomon Islands','iso' => 'SB','isd' => '677']);
		DB::table('country')->insert(['name' => 'Somalia','iso' => 'SO','isd' => '252']);
		DB::table('country')->insert(['name' => 'South Africa','iso' => 'ZA','isd' => '27']);
		DB::table('country')->insert(['name' => 'South Georgia and the South Sandwich Islands','iso' => 'GS','isd' => '500']);
		DB::table('country')->insert(['name' => 'Spain','iso' => 'ES','isd' => '34']);
		DB::table('country')->insert(['name' => 'Sri Lanka','iso' => 'LK','isd' => '94']);
		DB::table('country')->insert(['name' => 'Saint Helena, Ascension and Tristan da Cunha','iso' => 'SH','isd' => '290']);
		DB::table('country')->insert(['name' => 'St. Pierre and Miquelon','iso' => 'PM','isd' => '508']);
		DB::table('country')->insert(['name' => 'Sudan','iso' => 'SD','isd' => '249']);
		DB::table('country')->insert(['name' => 'Suriname','iso' => 'SR','isd' => '597']);
		DB::table('country')->insert(['name' => 'Svalbard and Jan Mayen Islands','iso' => 'SJ','isd' => '47']);
		DB::table('country')->insert(['name' => 'Swaziland','iso' => 'SZ','isd' => '268']);
		DB::table('country')->insert(['name' => 'Sweden','iso' => 'SE','isd' => '46']);
		DB::table('country')->insert(['name' => 'Switzerland','iso' => 'CH','isd' => '41']);
		DB::table('country')->insert(['name' => 'Syrian Arab Republic','iso' => 'SY','isd' => '963']);
		DB::table('country')->insert(['name' => 'Taiwan','iso' => 'TW','isd' => '886']);
		DB::table('country')->insert(['name' => 'Tajikistan','iso' => 'TJ','isd' => '992']);
		DB::table('country')->insert(['name' => 'Tanzania, United Republic of','iso' => 'TZ','isd' => '255']);
		DB::table('country')->insert(['name' => 'Thailand','iso' => 'TH','isd' => '66']);
		DB::table('country')->insert(['name' => 'Togo','iso' => 'TG','isd' => '228']);
		DB::table('country')->insert(['name' => 'Tokelau','iso' => 'TK','isd' => '690']);
		DB::table('country')->insert(['name' => 'Tonga','iso' => 'TO','isd' => '676']);
		DB::table('country')->insert(['name' => 'Trinidad and Tobago','iso' => 'TT','isd' => '1-868']);
		DB::table('country')->insert(['name' => 'Tunisia','iso' => 'TN','isd' => '216']);
		DB::table('country')->insert(['name' => 'Turkey','iso' => 'TR','isd' => '90']);
		DB::table('country')->insert(['name' => 'Turkmenistan','iso' => 'TM','isd' => '993']);
		DB::table('country')->insert(['name' => 'Turks and Caicos Islands','iso' => 'TC','isd' => '1-649']);
		DB::table('country')->insert(['name' => 'Tuvalu','iso' => 'TV','isd' => '688']);
		DB::table('country')->insert(['name' => 'Uganda','iso' => 'UG','isd' => '256']);
		DB::table('country')->insert(['name' => 'Ukraine','iso' => 'UA','isd' => '380']);
		DB::table('country')->insert(['name' => 'United Arab Emirates','iso' => 'AE','isd' => '971']);
		DB::table('country')->insert(['name' => 'United Kingdom','iso' => 'GB','isd' => '44']);
		DB::table('country')->insert(['name' => 'United States','iso' => 'US','isd' => '1']);
		DB::table('country')->insert(['name' => 'United States Minor Outlying Islands','iso' => 'UM','isd' => '246']);
		DB::table('country')->insert(['name' => 'Uruguay','iso' => 'UY','isd' => '598']);
		DB::table('country')->insert(['name' => 'Uzbekistan','iso' => 'UZ','isd' => '998']);
		DB::table('country')->insert(['name' => 'Vanuatu','iso' => 'VU','isd' => '678']);
		DB::table('country')->insert(['name' => 'Vatican City State (Holy See)','iso' => 'VA','isd' => '379']);
		DB::table('country')->insert(['name' => 'Venezuela','iso' => 'VE','isd' => '58']);
		DB::table('country')->insert(['name' => 'Vietnam','iso' => 'VN','isd' => '84']);
		DB::table('country')->insert(['name' => 'Virgin Islands (British)','iso' => 'VG','isd' => '1-284']);
		DB::table('country')->insert(['name' => 'Virgin Islands (U.S.)','iso' => 'VI','isd' => '1-340']);
		DB::table('country')->insert(['name' => 'Wallis and Futuna Islands','iso' => 'WF','isd' => '681']);
		DB::table('country')->insert(['name' => 'Western Sahara','iso' => 'EH','isd' => '212']);
		DB::table('country')->insert(['name' => 'Yemen','iso' => 'YE','isd' => '967']);
		DB::table('country')->insert(['name' => 'Serbia','iso' => 'RS','isd' => '381']);
		DB::table('country')->insert(['name' => 'Zambia','iso' => 'ZM','isd' => '260']);
		DB::table('country')->insert(['name' => 'Zimbabwe','iso' => 'ZW','isd' => '263']);
		DB::table('country')->insert(['name' => 'Aaland Islands','iso' => 'AX','isd' => '358']);
		DB::table('country')->insert(['name' => 'Palestine','iso' => 'PS','isd' => '970']);
		DB::table('country')->insert(['name' => 'Montenegro','iso' => 'ME','isd' => '382']);
		DB::table('country')->insert(['name' => 'Guernsey','iso' => 'GG','isd' => '44-1481']);
		DB::table('country')->insert(['name' => 'Isle of Man','iso' => 'IM','isd' => '44-1624']);
		DB::table('country')->insert(['name' => 'Jersey','iso' => 'JE','isd' => '44-1534']);
		DB::table('country')->insert(['name' => 'Curaçao','iso' => 'CW','isd' => '599']);
		DB::table('country')->insert(['name' => 'Ivory Coast','iso' => 'CI','isd' => '225']);
		DB::table('country')->insert(['name' => 'Kosovo','iso' => 'XK','isd' => '383']);
    }
}
